import { OccasionType, OccasionTheme } from '../types';

export const occasions: Record<OccasionType, OccasionTheme> = {
  birthday: {
    name: { en: 'Birthday', ar: 'عيد ميلاد' },
    colors: {
      primary: '#FF6B9D',
      secondary: '#FDB44B',
      accent: '#4ECDC4',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      text: '#FFFFFF',
    },
    animation: 'confetti',
    decorations: ['🎈', '🎂', '🎉', '🎊'],
  },
  'mothers-day': {
    name: { en: "Mother's Day", ar: 'عيد الأم' },
    colors: {
      primary: '#FFB7C5',
      secondary: '#F8E8E8',
      accent: '#D4A5A5',
      background: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
      text: '#6B4F4F',
    },
    animation: 'hearts',
    decorations: ['💐', '🌸', '💕', '🌹'],
  },
  ramadan: {
    name: { en: 'Ramadan', ar: 'رمضان' },
    colors: {
      primary: '#1A365D',
      secondary: '#D4AF37',
      accent: '#4A5568',
      background: 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)',
      text: '#F7FAFC',
    },
    animation: 'moon',
    decorations: ['🌙', '⭐', '🕌', '✨'],
  },
  'eid-fitr': {
    name: { en: 'Eid Al-Fitr', ar: 'عيد الفطر' },
    colors: {
      primary: '#2D5F3F',
      secondary: '#D4AF37',
      accent: '#48BB78',
      background: 'linear-gradient(135deg, #134e5e 0%, #71b280 100%)',
      text: '#F7FAFC',
    },
    animation: 'curtain',
    decorations: ['🌙', '⭐', '🕌', '✨'],
  },
  'eid-adha': {
    name: { en: 'Eid Al-Adha', ar: 'عيد الأضحى' },
    colors: {
      primary: '#2D5F3F',
      secondary: '#D4AF37',
      accent: '#48BB78',
      background: 'linear-gradient(135deg, #134e5e 0%, #71b280 100%)',
      text: '#F7FAFC',
    },
    animation: 'curtain',
    decorations: ['🌙', '⭐', '🕌', '🐑'],
  },
  christmas: {
    name: { en: 'Christmas', ar: 'عيد الميلاد' },
    colors: {
      primary: '#C41E3A',
      secondary: '#165B33',
      accent: '#FFD700',
      background: 'linear-gradient(135deg, #2c5364 0%, #203a43 0%, #0f2027 100%)',
      text: '#FFFFFF',
    },
    animation: 'snow',
    decorations: ['🎄', '❄️', '⛄', '🎅'],
  },
  graduation: {
    name: { en: 'Graduation', ar: 'التخرج' },
    colors: {
      primary: '#1A365D',
      secondary: '#D4AF37',
      accent: '#2C5282',
      background: 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)',
      text: '#F7FAFC',
    },
    animation: 'celebrate',
    decorations: ['🎓', '📜', '⭐', '🎉'],
  },
  wedding: {
    name: { en: 'Wedding / Engagement', ar: 'الزواج / الخطوبة' },
    colors: {
      primary: '#FFFFFF',
      secondary: '#D4AF37',
      accent: '#F7FAFC',
      background: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
      text: '#2D3748',
    },
    animation: 'elegant',
    decorations: ['💍', '💐', '🤍', '✨'],
  },
  'new-baby': {
    name: { en: 'New Baby', ar: 'مولود جديد' },
    colors: {
      primary: '#90CDF4',
      secondary: '#FBB6CE',
      accent: '#FED7E2',
      background: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
      text: '#2D3748',
    },
    animation: 'bounce',
    decorations: ['👶', '⭐', '🍼', '🎀'],
  },
  love: {
    name: { en: 'Love / Apology', ar: 'حب / اعتذار' },
    colors: {
      primary: '#F56565',
      secondary: '#FC8181',
      accent: '#FEB2B2',
      background: 'linear-gradient(135deg, #eb3349 0%, #f45c43 100%)',
      text: '#FFFFFF',
    },
    animation: 'heartbeat',
    decorations: ['❤️', '💕', '💖', '🌹'],
  },
  sympathy: {
    name: { en: 'Prayer / Sympathy', ar: 'دعاء / مواساة' },
    colors: {
      primary: '#A0AEC0',
      secondary: '#CBD5E0',
      accent: '#E2E8F0',
      background: 'linear-gradient(135deg, #e0e0e0 0%, #f5f5f5 100%)',
      text: '#2D3748',
    },
    animation: 'calm',
    decorations: ['🕊️', '🤲', '✨', '💫'],
  },
};
